DROP TABLE IF EXISTS TB_CARRO;
 
CREATE TABLE TB_CARRO (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  marca VARCHAR(100) NOT NULL,
  modelo VARCHAR(100) NOT NULL,
  ano INT NOT NULL,
  placa VARCHAR(7) NOT NULL,
  status VARCHAR(20) NOT NULL,
  data_criacao timestamp DEFAULT NULL,
  data_atualizacao timestamp DEFAULT NULL
);